# Generated by Django 5.1 on 2024-11-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Facturas',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('estudiante', models.IntegerField()),
        #         ('institucion_asociada', models.IntegerField()),
        #         ('respondable_economico', models.IntegerField()),
        #         ('fecha_limite_pago', models.DateField()),
        #         ('fecha_incial', models.DateField()),
        #         ('valor', models.FloatField()),
        #     ],
        #     options={
        #         'db_table': 'facturas',
        #     },
        # ),
    ]
